package com.geospatial.processing.auth

import java.security.KeyFactory
import java.security.Signature
import java.security.spec.X509EncodedKeySpec
import java.time.Instant
import java.util.Base64

object LicenseManager {

    // Paste the PUBLIC KEY generated by your KeyGeneratorUtil here.
    // It is completely safe to hardcode this in the client app.
    private const val PUBLIC_KEY_BASE64 = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqhUtIYQVcgo/t53E7vOTJXd7ghj9OkXzhIYsJvFBRxqyLX0qCYBALgaH/5kTjayBNvPzrVaRoTNyGYhmhDBtxfcrZPC/KdY3HmYQNd4HT/+jfb9BNQUtl9hmE4eJNvj7r5fSn+ahA2bb0cLN2uahUS4SS230034+95mvXqoMO0tXP3f8V2IqZKKVR6ZQ/I9MR0vpnzCaMuBFcBCKRd6BIRv8bqGIhBKYal7dDVdOv2FfPmNN8tJwLQx24bMosJuDlTMkmnsaaR9KOHrKJ4k3AG6FjC7rV9RhNc1Krmg9SaJM8xnSex42GRiEi8BttEdoW7bK+UY5nhviR1OskTcO3QIDAQAB"

    sealed class LicenseStatus {
        object Valid : LicenseStatus()
        object Expired : LicenseStatus()
        object InvalidMachine : LicenseStatus()
        object TamperedOrInvalid : LicenseStatus()
    }

    fun verifyLicense(licenseString: String): LicenseStatus {
        try {
            // 1. TRIM THE INPUT to remove invisible newlines or spaces from copy-pasting
            val cleanLicense = licenseString.trim()

            val parts = cleanLicense.split(".")
            if (parts.size != 2) {
                println("DEBUG: License string doesn't have exactly 2 parts separated by a dot.")
                return LicenseStatus.TamperedOrInvalid
            }

            val encodedPayload = parts[0]
            val encodedSignature = parts[1]

            // ... (Keep the middle cryptographic verification part exactly the same) ...

            val keyBytes = Base64.getDecoder().decode(PUBLIC_KEY_BASE64)
            val spec = java.security.spec.X509EncodedKeySpec(keyBytes)
            val keyFactory = KeyFactory.getInstance("RSA")
            val publicKey = keyFactory.generatePublic(spec)

            val rsaSignature = Signature.getInstance("SHA256withRSA")
            rsaSignature.initVerify(publicKey)
            //rsaSignature.update(encodedPayload.toByteArray())

            val rawPayloadBytes = Base64.getDecoder().decode(encodedPayload)
            rsaSignature.update(rawPayloadBytes)

            val signatureBytes = Base64.getDecoder().decode(encodedSignature)
            if (!rsaSignature.verify(signatureBytes)) {
                println("DEBUG: Cryptographic signature verification failed! The keys do not match.")
                return LicenseStatus.TamperedOrInvalid
            }

            val payloadString = String(Base64.getDecoder().decode(encodedPayload))
            val payloadParts = payloadString.split("|")

            if (payloadParts.size != 2) return LicenseStatus.TamperedOrInvalid

            val licenseMachineId = payloadParts[0]
            val expirationEpoch = payloadParts[1].toLong()

            if (licenseMachineId != HardwareUtil.getMachineId()) return LicenseStatus.InvalidMachine
            if (java.time.Instant.now().toEpochMilli() > expirationEpoch) return LicenseStatus.Expired

            return LicenseStatus.Valid

        } catch (e: Exception) {
            // 2. PRINT THE EXACT ERROR TO THE CONSOLE
            println("DEBUG: Crashed during verification!")
            e.printStackTrace()
            return LicenseStatus.TamperedOrInvalid
        }
    }
}